name: GitHub Build and Testing
run-name: Build and Testing
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: build v8
	  run: |
          ./build-v8.sh
          shell: bash  
      - name: build tea
        run: |
          ./build-tea.py build
      - name: test
        run: |
          ./test.sh
      - run: echo "ğŸ This job's status is ${{ job.status }}."