name: GitHub Build and Testing
run-name: Build and Testing
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: install update
        run: |
          sudo apt-get update
      - name: install gdlib
        run: |
          sudo apt-get install libgd-tools libgd-dev
      - name: install libz
        run: |
          sudo apt-get install zlib1g-dev
      - name: install ssl
        run: |
          sudo apt-get install libssl-dev
      - uses: actions/checkout@v2
      - name: build v8
        run: |
          ./build-v8.sh
      - name: build tea
        run: |
          ./build-tea.py build
      - name: test
        run: |
          ./test.sh
      - run: echo "ğŸ This job's status is ${{ job.status }}."