name: GitHub Build and Testing
run-name: Build and Testing
on: [push]
jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: install update
        run: |
          sudo apt-get update
      - name: remove nginx
        run: |
          sudo apt-get remove nginx
      - name: remove libgd3
        run: |
          sudo apt-get remove libgd3
      - name: install libraries
        run: |
          sudo apt-get install -yq libgd-tools libgd-dev zlib1g-dev libfcgi-dev libx32stdc++6-amd64-cross libssl-dev
      - uses: actions/checkout@v2
      - name: build v8
        run: |
          ./build-v8.sh
      - name: build tea
        run: |
          ./build-tea.py build
      - name: test
        run: |
          ./test.sh
      - name: make-release
        run: |
          ./make-release.sh
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: teajs-ubuntu
          path: |
            deploy
      - run: echo "üçè This job's status is ${{ job.status }}."
  MacOS:
    runs-on: macos-latest
    steps:
      - name: install brew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      - name: install libraries
        run: |
          brew install gd gdbm gdk-pixbuf libpq fcgi zlib-ng libssl-dev
      - uses: actions/checkout@v2
      - name: build v8
        run: |
          ./build-v8.sh
      - name: build tea
        run: |
          ./build-tea.py build
      - name: test
        run: |
          ./test.sh
      - name: make-release
        run: |
          ./make-release.sh
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: teajs-macos
          path: |
            deploy
      - run: echo "üçè This job's status is ${{ job.status }}."