name: GitHub Assembly and Testing
run-name: Assembly and Testing
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: |
          ./build-tea.py clean
	- run: ./build-v8.sh
        shell: bash  
      - run: ./build-tea.py build
      - run: ./test.sh
      - run: echo "ğŸ This job's status is ${{ job.status }}."